/* Essentially a template right here */
LOAD DATA INFILE 'dataCSV/user.csv'
INTO TABLE user
COLUMNS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;
